/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CardsCardIdImport } from './routes/cards/$cardId'

// Create Virtual Routes

const FavouritesLazyImport = createFileRoute('/favourites')()

// Create/Update Routes

const FavouritesLazyRoute = FavouritesLazyImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/favourites.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CardsCardIdRoute = CardsCardIdImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesLazyRoute
  '/cards/$cardId': typeof CardsCardIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesLazyRoute
  '/cards/$cardId': typeof CardsCardIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesLazyRoute
  '/cards/$cardId': typeof CardsCardIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favourites' | '/cards/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favourites' | '/cards/$cardId'
  id: '__root__' | '/' | '/favourites' | '/cards/$cardId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesLazyRoute: typeof FavouritesLazyRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesLazyRoute: FavouritesLazyRoute,
  CardsCardIdRoute: CardsCardIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favourites",
        "/cards/$cardId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favourites": {
      "filePath": "favourites.lazy.tsx"
    },
    "/cards/$cardId": {
      "filePath": "cards/$cardId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
